AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - ".git/**/*"
    - "docs/**/*"

#
# RuboCop built-in settings.
#   For documentation on all settings see: https://docs.rubocop.org/en/stable
#

# Trailing periods.
Layout/DotPosition:
  EnforcedStyle: trailing

# Turn on auto-correction of equals alignment.
Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# Use a table layout for hashes
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Soften limits
Layout/LineLength:
  Max: 128
  Exclude:
    - "**/test/**/*"

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# TODO: Soften Limits for phase 1 only
Metrics/AbcSize:
  Max: 40

# Support long block lengths for tests
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "**/*/cli.rb"
  ExcludedMethods:
    - "aasm"
    - "included"

# Soften limits
Metrics/ClassLength:
  Max: 250
  Exclude:
    - "test/**/*"

# TODO: Soften Limits for phase 1 only
Metrics/CyclomaticComplexity:
  Max: 15

# Soften limits
Metrics/MethodLength:
  Max: 50

# Soften limits
Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  CountKeywordArgs: false

# TODO: Soften Limits for phase 1 only
Metrics/PerceivedComplexity:
  Max: 21

# Initialization Vector abbreviation
Naming/MethodParameterName:
  AllowedNames: ['iv', '_', 'io', 'ap']

# Does not allow Symbols to load
Security/YAMLLoad:
  AutoCorrect: false

# Needed for testing DateTime
Style/DateTime:
  Exclude: ["test/**/*"]

# TODO: Soften Limits for phase 1 only
Style/Documentation:
  Enabled: false

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Ruby 3 compatibility feature
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

# Incorrectly changes job.fail to job.raise
Style/SignalException:
  Enabled: false

# Since English may not be loaded, cannot force its use.
Style/SpecialGlobalVars:
  Enabled: false

# Make it easier for developers to move between Elixir and Ruby.
Style/StringLiterals:
  EnforcedStyle: double_quotes
